stages:
  - build
  - tag-latest

variables:
  LOGGING_LEVEL: DEBUG
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

Build Image:
  image: jonoh/docker-buildx-qemu
  stage: build
  services:
    - docker:19.03.0-dind
  before_script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME} || echo 'No previous image to download as a base'
    - docker build -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME}" --build-arg SIT_PYPI_USER_VAR="$SIT_PYPI_USER" --build-arg SIT_PYPI_PASS_VAR="$SIT_PYPI_PASS" .
    - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME}"
  except:
    - tags
  when: manual

Tag Latest:
  stage: tag-latest
  image: jonoh/docker-buildx-qemu

  services:
    - docker:19.03.0-dind
  before_script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME}"
    - docker tag "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME}" $CI_REGISTRY_IMAGE:latest
    - docker push "$CI_REGISTRY_IMAGE:latest"
