version: '2.3'
services:
  benchmark-platform-controller:
    privileged: true
    runtime: nvidia
    image: benchmark-platform-controller:latest
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    volumes:
      - ./:/benchmark-platform-controller
      - /var/run/docker.sock:/var/run/docker.sock
      # args:
      #   SIT_PYPI_USER_VAR: ${SIT_PYPI_USER}
      #   SIT_PYPI_PASS_VAR: ${SIT_PYPI_PASS}