version: '2.3'
services:
  tasks-redis:
    image: redis:5.0.3
    ports:
      - "6378:6379"

  db:
    image: postgres:9.6
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

  benchmark-platform-controller:
    depends_on:
      - tasks-redis

    privileged: true
    image: registry.insight-centre.org/sit/mps/benchmark-platform-controller:latest
    command: /service/entrypoint.sh
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    volumes:
      - ./scripts:/service/scripts
      - ./configs.json:/service/configs.json
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=tasks-redis
      - REDIS_PORT=6379
      - GITLAB_USER=${GITLAB_USER}
      - GITLAB_PASS=${GITLAB_PASS}
      - TARGET_COMPOSE_OVERRIDE_FILENAME=${TARGET_COMPOSE_OVERRIDE_FILENAME}
      - SLEEP_AFTER_TARGET_STARTUP=${SLEEP_AFTER_TARGET_STARTUP}
      - SLEEP_AFTER_BENCHMARK_STARTUP=${SLEEP_AFTER_BENCHMARK_STARTUP}
      - TARGET_SYSTEM_JSON_CONFIG_FILENAME=${TARGET_SYSTEM_JSON_CONFIG_FILENAME}
      - BENCHMARK_JSON_CONFIG_FILENAME=${BENCHMARK_JSON_CONFIG_FILENAME}
      - DEFAULT_BENCHMARK_JSON_FILE=/service/configs.json
      - WEBHOOK_BASE_URL=${WEBHOOK_BASE_URL}
      - DATA_DIR=/service/tmp
      - DATABASE_URL=${DATABASE_URL}
      - EXECUTION_TIMEOUT=${EXECUTION_TIMEOUT}
